### ISSUE TITLE
Fix code scanning alert - Hard-coded credentials

### ISSUE THREAD

**Issue by me1kimu** [ElProConLag/dw_2023#1]
Replace the hard-coded credential with the secret found in **Settings > Security > Secrets and variables**.
More information below.

https://github.com/ElProConLag/dw_2023/security/code-scanning/1
https://docs.github.com/actions/security-guides/encrypted-secrets

**Comment by ElProConLag** [comment]
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/24
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/25
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/26
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/29
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/34
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/35
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/36
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/38
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/39
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/43
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/44
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/45
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/46
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/47
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/48
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/49
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/50
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/51
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/52
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/53
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/54

**Comment by me1kimu** [comment]
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/24
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/25
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/26
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/29
- [x] https://github.com/ElProConLag/dw_2023/security/code-scanning/34
- [x] https://github.com/ElProConLag/dw_2023/security/code-scanning/35
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/36
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/38
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/39
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/43
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/44
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/45
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/46
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/47
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/48
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/49
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/50
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/51
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/52
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/53
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/54

**Comment by me1kimu** [comment]
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/55
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/56
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/57
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/58
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/59
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/60
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/62
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/63
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/64
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/65
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/66
- [ ] https://github.com/ElProConLag/dw_2023/security/code-scanning/67
